HTTP5101-Cumulative Project/Controllers/ClassController.cs
using HTTP5101_Cumulative_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HTTP5101_Cumulative_Project.Controllers
{
    public class ClassController : Controller
    {
        // Controller which allows us to access methods from ClassDataController
        private ClassDataController Controller = new ClassDataController();

        public ActionResult Index(string Search)
        {
            IEnumerable<Class> ClassesList = Controller.ListClasses(Search);
            ViewBag.Title = "Class List Page";
            ViewData["Search"] = Search;

            return View(ClassesList);
        }

        public ActionResult Details(int id)
        {
            Class ClassDetails = Controller.ClassDetails(id);
            ViewBag.Title = "Class Details Page";

            return View(ClassDetails);
        }

        public ActionResult ConfirmDelete(int id)
        {
            Class ClassDetails = Controller.ClassDetails(id);
            ViewBag.Title = "Confirm Delete Page";

            return View(ClassDetails);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            Controller.DeleteClass(id);
            return RedirectToAction("Index");
        }

        //GET : /Teacher/New
        public ActionResult New()
        {
            return View();
        }

        //GET : /Teacher/Ajax_New
        public ActionResult Ajax_New()
        {
            return View();
        }

        //POST : /Teacher/Create
        [HttpPost]
        public ActionResult Create(Class ClassObj)
        {
            if (
                    String.IsNullOrEmpty(ClassObj.ClassCode) ||
                    String.IsNullOrEmpty(ClassObj.ClassName) ||
                    String.IsNullOrEmpty(ClassObj.StartDate.ToString()) ||
                    String.IsNullOrEmpty(ClassObj.EndDate.ToString())
               )
                return RedirectToAction("New");

            int InsertedId = Controller.AddClass(ClassObj);

            return RedirectToAction(String.Concat("Details/", InsertedId));
        }
    }
}

HTTP5101-Cumulative Project/Views/Class/Details.cshtml
@model HTTP5101_Cumulative_Project.Models.Class
@{
    ViewBag.Title = "ClassDetails";
}

<h2>Class Details</h2>

<div>
    <dl class="dl-horizontal">
        <dt>
            Class Id
        </dt>
        <dd>
            @Model.ClassId
        </dd>

        <dt>
            Class Name
        </dt>
        <dd>
            @Model.ClassName
        </dd>

        <dt>
            Class Code
        </dt>
        <dd>
            @Model.ClassCode
        </dd>

        <dt>
            Start Date
        </dt>
        <dd>
            @Model.StartDate.ToShortDateString()
        </dd>

        <dt>
            Enrol Date
        </dt>
        <dd>
            @Model.EndDate.ToShortDateString()
        </dd>

        <dt>
            Teacher
        </dt>
        <dd>
            @Model.TeacherName
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-primary" })
</p>

HTTP5101-Cumulative Project/Views/Class/Index.cshtml
@model IEnumerable<HTTP5101_Cumulative_Project.Models.Class>
@{
    ViewBag.Title = "Index";
}

<h2>Classes List Page</h2>

<div class="row">
    <div class="col-12">
        <form asp-controller="Class" asp-action="Index">
            <p>
                Search: <input type="text" name="Search" value="@ViewData["Search"]" />
                <input type="submit" value="Search" />
            </p>
        </form>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table border="1">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Class Code</th>
                    <th>Class Name</th>
                    <th>Start Date</th>
                    <th>End date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{ int i = 1;}
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td>@item.ClassCode</td>
                        <td>@item.ClassName</td>
                        <td>@item.StartDate.ToShortDateString()</td>
                        <td>@item.EndDate.ToShortDateString()</td>
                        <td>
                            @Html.ActionLink("View", "Details", new { id = @item.ClassId }, new { @class = "btn btn-primary" })
                        </td>
                    </tr>

                    i++;
                }
            </tbody>
        </table>
    </div>
</div>

<style>
    table {
        width: 100%;
    }

    thead, tbody, tfoot, tr, td, th {
        border-width: 1px;
        padding: 0.25em;
    }
</style>